;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Default
DestinationPath=Content/Localization/Default
ManifestName=Default.manifest
ArchiveName=Default.archive
CulturesToGenerate=en
CulturesToGenerate=zh

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=Default.csv

