;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Blueprints/AbilitySystem/GameplayTags/DP_Message.DP_Message
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Enemy.Slingshot",DevComment="")
+GameplayTagList=(Tag="Cooldown.HitReact",DevComment="")
+GameplayTagList=(Tag="Cooldown.Stun",DevComment="")
+GameplayTagList=(Tag="Effects.Cost.LightningShockPeriodic",DevComment="")
+GameplayTagList=(Tag="Effects.Reducing.FireStacking",DevComment="")
+GameplayTagList=(Tag="Effects.Stacking.Fire",DevComment="")
+GameplayTagList=(Tag="Effects.Stun",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Event.Montage.FireBolt",DevComment="")
+GameplayTagList=(Tag="GameplayCue.LevelUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MeleeImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.OnFire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.PeriodicHealth",DevComment="")
+GameplayTagList=(Tag="GameplayCue.PeriodicMana",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Stun",DevComment="")
+GameplayTagList=(Tag="GameplayCue.TestCue",DevComment="")
+GameplayTagList=(Tag="HitReact",DevComment="")
+GameplayTagList=(Tag="ImmunteAbility.HitReact",DevComment="")

