// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "UObject/Interface.h"
#include "CombatInterface.generated.h"

class UAnimMontage;
class UNiagaraSystem;
class USoundBase;

USTRUCT(BlueprintType)
struct FTaggedMontage {
    GENERATED_BODY()

    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
    UAnimMontage* Montage;

    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
    FGameplayTag MontageTag;

    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
    USoundBase* ImpactSound;
};

// This class does not need to be modified.
UINTERFACE(MinimalAPI, BlueprintType)
class UCombatInterface : public UInterface
{
	GENERATED_BODY()
};

/**
 * 
 */
class AURA_API ICombatInterface
{
	GENERATED_BODY()

	// Add interface functions to this class. This is the class that will be inherited to implement this interface.
public:
    virtual int32 GetPlayerLevel() const;

    UFUNCTION(BlueprintNativeEvent, BlueprintCallable)
    FVector GetCombatSocketLocation(const FGameplayTag& MontageTag);

    // Blueprint implement event can't not be virtual ?
    UFUNCTION(BlueprintImplementableEvent, BlueprintCallable)
    void UpdateFacingTarget(const FVector& Target);

    // BlueprintNativeEvent: 
    /// This function is designed to be overridden by a blueprint, but also has a native implementation.
    /// Provide a body named [FunctionName]_Implementation instead of [FunctionName]; the autogenerated
    /// code will include a thunk that calls the implementation method when necessary.
    UFUNCTION(BlueprintNativeEvent, BlueprintCallable)
    UAnimMontage *GetHitReactMontage();

    virtual void Die() = 0;

    UFUNCTION(BlueprintNativeEvent, BlueprintCallable)
    bool IsDead() const;

    UFUNCTION(BlueprintNativeEvent, BlueprintCallable)
    AActor* GetAvtar();

    UFUNCTION(BlueprintNativeEvent, BlueprintCallable)
    TArray<FTaggedMontage> GetAttackMontages();

    UFUNCTION(BlueprintNativeEvent, BlueprintCallable)
    UNiagaraSystem* GetBloodEffect();
};
